# ansible/roles/tasks/jenkins/main.yml - Install and Configure Jenkins
- name: Install Java 17 (required for Jenkins)
  ansible.builtin.apt:
    name: openjdk-17-jdk
    state: present
    update_cache: yes

- name: Create the directory for APT keyrings (secure Debian practice)
  ansible.builtin.file:
    path: /usr/share/keyrings
    state: directory
    mode: '0755'

- name: Download Jenkins GPG key to keyring file
  ansible.builtin.get_url:
    url: https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key
    dest: /usr/share/keyrings/jenkins-keyring.asc
    mode: '0644'
    # Use get_url for secure and idempotent key downloading

- name: Add Jenkins repository with signed-by
  ansible.builtin.apt_repository:
    repo: 'deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] https://pkg.jenkins.io/debian-stable binary/'
    state: present
    filename: jenkins
    update_cache: yes

- name: Install Jenkins package
  ansible.builtin.apt:
    name: jenkins
    state: present

- name: Ensure Jenkins service is running and enabled
  ansible.builtin.systemd:
    name: jenkins
    state: started
    enabled: yes