---
# ============================================
# Role: Kubernetes Worker Node Setup
# ============================================

- name: Ensure APT dependencies are installed
  become: yes
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
    state: present
    update_cache: yes

- name: Add Kubernetes GPG key
  become: yes
  ansible.builtin.shell: |
    curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.30/deb/Release.key | \
    sudo gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
  args:
    creates: /etc/apt/keyrings/kubernetes-apt-keyring.gpg

- name: Add Kubernetes repository
  become: yes
  ansible.builtin.copy:
    dest: /etc/apt/sources.list.d/kubernetes.list
    content: |
      deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] \
      https://pkgs.k8s.io/core:/stable:/v1.30/deb/ /

- name: Update apt cache
  become: yes
  ansible.builtin.apt:
    update_cache: yes

- name: Install Kubernetes components (kubeadm, kubelet, kubectl)
  become: yes
  ansible.builtin.apt:
    name:
      - kubeadm
      - kubelet
      - kubectl
    state: present

- name: Disable swap (required by Kubernetes)
  become: yes
  ansible.builtin.shell: |
    swapoff -a
    sed -i '/swap/d' /etc/fstab
  args:
    warn: false

- name: Enable IP forwarding
  become: yes
  ansible.builtin.shell: |
    echo "net.ipv4.ip_forward = 1" | sudo tee /etc/sysctl.d/k8s.conf
    sysctl --system

# The join command is provided by the master node output
- name: Join the Kubernetes cluster
  become: yes
  ansible.builtin.shell: "{{ hostvars[groups['k8s_master'][0]].join_cmd.stdout }}"
  args:
    creates: /etc/kubernetes/kubelet.conf
  when: hostvars[groups['k8s_master'][0]].join_cmd is defined
