---
# ============================================
# Role: Kubernetes Master Node Setup
# ============================================

- name: Ensure APT dependencies are installed
  become: yes
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
    state: present
    update_cache: yes

- name: Add Kubernetes GPG key
  become: yes
  ansible.builtin.shell: |
    curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.30/deb/Release.key | \
    sudo gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
  args:
    creates: /etc/apt/keyrings/kubernetes-apt-keyring.gpg

- name: Add Kubernetes repository
  become: yes
  ansible.builtin.copy:
    dest: /etc/apt/sources.list.d/kubernetes.list
    content: |
      deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] \
      https://pkgs.k8s.io/core:/stable:/v1.30/deb/ /

- name: Update apt cache
  become: yes
  ansible.builtin.apt:
    update_cache: yes

- name: Install Kubernetes components (kubeadm, kubelet, kubectl)
  become: yes
  ansible.builtin.apt:
    name:
      - kubeadm
      - kubelet
      - kubectl
    state: present

- name: Disable swap (required by Kubernetes)
  become: yes
  ansible.builtin.shell: |
    swapoff -a
    sed -i '/swap/d' /etc/fstab
  args:
    warn: false

- name: Enable IP forwarding
  become: yes
  ansible.builtin.shell: |
    echo "net.ipv4.ip_forward = 1" | sudo tee /etc/sysctl.d/k8s.conf
    sysctl --system

- name: Initialize Kubernetes master node
  become: yes
  ansible.builtin.command: kubeadm init --pod-network-cidr=192.168.0.0/16
  args:
    creates: /etc/kubernetes/admin.conf
  register: kubeadm_init

- name: Set up kubeconfig for the current user
  become: yes
  ansible.builtin.shell: |
    mkdir -p $HOME/.kube
    cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
    chown $(id -u):$(id -g) $HOME/.kube/config
  args:
    executable: /bin/bash

- name: Install Calico network plugin
  become: yes
  ansible.builtin.shell: |
    kubectl apply -f https://docs.projectcalico.org/manifests/calico.yaml
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf

- name: Display cluster join command
  become: yes
  ansible.builtin.shell: kubeadm token create --print-join-command
  register: join_cmd

- name: Show worker join command
  ansible.builtin.debug:
    msg: "Worker nodes can join using: {{ join_cmd.stdout }}"
