---
# ==========================================================
# Global Variables for All Roles
# ==========================================================

# ----------------------------------------------------------
# General Settings
# ----------------------------------------------------------
ansible_user: ubuntu                     # Default SSH user (update if needed)
ansible_ssh_private_key_file: ~/.ssh/id_rsa  # Update if using custom key
ansible_python_interpreter: /usr/bin/python3

# ----------------------------------------------------------
# Jenkins Configuration
# ----------------------------------------------------------
jenkins_repo_key_url: https://pkg.jenkins.io/debian/jenkins.io-2023.key
jenkins_repo_url: https://pkg.jenkins.io/debian-stable
jenkins_pkg_name: jenkins
jenkins_service_name: jenkins
jenkins_port: 8080

# ----------------------------------------------------------
# Monitoring Stack (Prometheus + Grafana)
# ----------------------------------------------------------
prometheus_version: "2.52.0"
prometheus_dir: /opt/prometheus
prometheus_user: prometheus
prometheus_port: 9090

node_exporter_version: "1.8.1"
node_exporter_dir: /opt/node_exporter
node_exporter_port: 9100

grafana_repo_key_url: https://packages.grafana.com/gpg.key
grafana_repo_url: https://packages.grafana.com/oss/deb
grafana_pkg_name: grafana
grafana_service_name: grafana-server
grafana_port: 3000

# ----------------------------------------------------------
# Kubernetes Cluster Configuration
# ----------------------------------------------------------
kubernetes_version: "1.30.0-00"
kubernetes_pod_network_cidr: "10.244.0.0/16"

# This join command will be dynamically written by the master role
kubernetes_join_command_file: "/tmp/kube_join_command.sh"

# ----------------------------------------------------------
# Docker Configuration (Used in Multiple Roles)
# ----------------------------------------------------------
docker_packages:
  - ca-certificates
  - curl
  - gnupg
  - lsb-release

docker_gpg_key_url: https://download.docker.com/linux/ubuntu/gpg
docker_repo_line: "deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable"

# ----------------------------------------------------------
# Firewall Rules (Optional)
# ----------------------------------------------------------
firewall_allowed_ports:
  - 22     # SSH
  - 80     # HTTP
  - 443    # HTTPS
  - "{{ jenkins_port }}"
  - "{{ grafana_port }}"
  - "{{ prometheus_port }}"
  - "{{ node_exporter_port }}"
