# ansible/roles/tasks/kubernetes/main.yml (NEW)
- name: Install dependencies
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      # Also add 'gnupg' to handle key conversion
      - gnupg 
    state: present
    update_cache: yes

- name: Download Kubernetes GPG key and convert to keyring format
  ansible.builtin.shell: 
    # Use gpg --dearmor to convert the key to the modern binary keyring format
    cmd: curl -fsSL https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo gpg --dearmor -o /etc/apt/keyrings/kubernetes-archive-keyring.gpg
    creates: /etc/apt/keyrings/kubernetes-archive-keyring.gpg
  args:
    warn: false # Suppress warning about using shell

- name: Add Kubernetes apt repo with signed-by
  ansible.builtin.apt_repository:
    repo: 'deb [signed-by=/etc/apt/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main'
    state: present
    filename: kubernetes
    update_cache: yes

- name: Install kubeadm, kubelet, kubectl
  ansible.builtin.apt:
    name:
      - kubelet
      - kubeadm
      - kubectl
    state: present

- name: Disable swap (required for Kubernetes)
  ansible.builtin.command: swapoff -a

- name: Initialize Kubernetes master
  ansible.builtin.shell: kubeadm init
  when: inventory_hostname in groups['kubernetes_master']
  args:
    creates: /etc/kubernetes/admin.conf