# ==============================================================
# Global Variables for All Ansible Hosts
# Used by: Jenkins, Monitoring (Grafana/Prometheus), Kubernetes nodes
# ==============================================================

# -----------------------------
# SSH / Connection Settings
# -----------------------------
ansible_user: ubuntu
ansible_connection: ssh
ansible_ssh_private_key_file: ~/.ssh/id_rsa
ansible_become: yes
ansible_become_method: sudo

# -----------------------------
# Common Packages for All EC2s
# -----------------------------
common_packages:
  - curl
  - wget
  - unzip
  - git
  - apt-transport-https
  - ca-certificates
  - gnupg
  - lsb-release
  - python3
  - python3-pip

# -----------------------------
# Jenkins Variables
# -----------------------------
jenkins_repo_key_url: https://pkg.jenkins.io/debian-stable/jenkins.io.key
jenkins_repo_url: deb https://pkg.jenkins.io/debian-stable binary/
jenkins_package: jenkins
jenkins_port: 8080

# -----------------------------
# Monitoring (Prometheus + Grafana)
# -----------------------------
prometheus_version: "2.54.1"
prometheus_download_url: "https://github.com/prometheus/prometheus/releases/download/v{{ prometheus_version }}/prometheus-{{ prometheus_version }}.linux-amd64.tar.gz"

grafana_apt_repo: "deb https://packages.grafana.com/oss/deb stable main"
grafana_gpg_key: "https://packages.grafana.com/gpg.key"
grafana_service_name: grafana-server

# -----------------------------
# Kubernetes Variables
# -----------------------------
k8s_packages:
  - apt-transport-https
  - ca-certificates
  - curl
  - gpg
  - kubelet
  - kubeadm
  - kubectl
k8s_repo_key_url: https://pkgs.k8s.io/core:/stable:/v1.30/deb/Release.key
k8s_repo_url: "deb https://pkgs.k8s.io/core:/stable:/v1.30/deb/ /"
k8s_master_ip: "{{ hostvars['k8s_master_node'].ansible_host | default('127.0.0.1') }}"
pod_network_cidr: "10.244.0.0/16"

# -----------------------------
# Prometheus Service Configuration
# -----------------------------
prometheus_config_dir: /etc/prometheus
prometheus_data_dir: /var/lib/prometheus
prometheus_service_name: prometheus

# -----------------------------
# Grafana Configuration
# -----------------------------
grafana_port: 3000

# -----------------------------
# Miscellaneous
# -----------------------------
timezone: Asia/Kolkata
