---
- name: Install and configure Jenkins
  # Targets any instance group name that contains 'jenkins_server'
  # Example: tag_Name_Nitesh_netflix_clone_dev_jenkins_server
  hosts: tag_Name_*jenkins_server 
  become: yes
  vars:
    java_package: openjdk-17-jdk
  tasks:
    - name: Update system packages
      ansible.builtin.apt:
        update_cache: yes

    - name: Install Java (required for Jenkins)
      ansible.builtin.apt:
        name: "{{ java_package }}"
        state: present

    # Best Practice: Using apt_key is fine for simple scripts, 
    # but be aware of its security limitations.
    - name: Add Jenkins repository key
      ansible.builtin.apt_key:
        url: https://pkg.jenkins.io/debian/jenkins.io.key
        state: present

    - name: Add Jenkins repository
      ansible.builtin.apt_repository:
        repo: "deb https://pkg.jenkins.io/debian binary/"
        state: present

    - name: Install Jenkins
      ansible.builtin.apt:
        name: jenkins
        state: present
        update_cache: yes

    - name: Enable and start Jenkins service
      ansible.builtin.systemd:
        name: jenkins
        enabled: yes
        state: started

    - name: Print Jenkins initial admin password
      ansible.builtin.command: cat /var/lib/jenkins/secrets/initialAdminPassword
      register: jenkins_password
      changed_when: false
      # ⚠️ SECURITY: Prevent this sensitive value from appearing in CI/CD logs
      no_log: true 

    - name: Display Jenkins Admin Password
      ansible.builtin.debug:
        msg: "Jenkins Admin Password: {{ jenkins_password.stdout }}"
      # ⚠️ SECURITY: Prevent this sensitive value from appearing in CI/CD logs
      no_log: true