---
- name: Install and configure Jenkins
  hosts: tag_Name_jenkins-server
  become: yes
  vars:
    java_package: openjdk-17-jdk
  tasks:
    - name: Update system packages
      apt:
        update_cache: yes

    - name: Install Java (required for Jenkins)
      apt:
        name: "{{ java_package }}"
        state: present

    - name: Add Jenkins repository key
      apt_key:
        url: https://pkg.jenkins.io/debian/jenkins.io.key
        state: present

    - name: Add Jenkins repository
      apt_repository:
        repo: "deb https://pkg.jenkins.io/debian binary/"
        state: present

    - name: Install Jenkins
      apt:
        name: jenkins
        state: present
        update_cache: yes

    - name: Enable and start Jenkins service
      systemd:
        name: jenkins
        enabled: yes
        state: started

    - name: Print Jenkins initial admin password
      command: cat /var/lib/jenkins/secrets/initialAdminPassword
      register: jenkins_password
      changed_when: false

    - debug:
        msg: "Jenkins Admin Password: {{ jenkins_password.stdout }}"
