- name: Configure Jenkins Server
  hosts: jenkins
  become: yes
  roles:
    - jenkins

- name: Configure Monitoring Stack
  hosts: monitoring
  become: yes
  roles:
    - monitoring

- name: Configure Kubernetes Cluster
  hosts: kubernetes_master
  become: yes
  roles:
    - kubernetes
